version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password.1
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    healthcheck:
      test: ["CMD", "pg_isready","-U", "postgres"]
      interval: 5s
      retries: 5
    ports:
      - "5433:5432"